version: '3.7'
services:
  db:
    image: mongo
    container_name : makeen-db
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=makeen
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Password1
      - IMPORT_FROM_VOLUME=true
    ports:
      - '27017-27019:27017-27019'
    volumes: 
      - mongoData:/data/db 
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
  makeen-poc:
    build:
        context: ./
        dockerfile: ./Dockerfile
    ports:
        - '8080:8080' 
    depends_on:
        - db
volumes:
  mongoData:
    driver: local